[project]
name = "aws-cloud-datamanagement-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Chin Xu Xin", email = "xchi0019@student.monash.edu" }
]
requires-python = ">=3.14"
dependencies = [
    "kagglehub>=1.0.2",
    "pandas>=3.0.5",
    "pathlib>=1.0.1",
    "psycopg2-binary>=2.9.12",
    "pyarrow>=25.0.1",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
aws-cloud-datamanagement-project = "aws_cloud_datamanagement_project:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
